"""Region pack manifest (ticket R1): bbox + geography/weather paths +
pack-tunable search knobs, generated by the same bbox-parametric ingest
scripts B7 Part 1 built (see `docs/region-pack-runbook.md`). `core/`
loads a pack *by reference* -- `core/lattice.py`/`core/corridors.py`/
`core/legs.py`/`core/optimiser.py` take `bbox`/`ref_lat_deg`/the lattice
tuning knobs as explicit, defaulted parameters (never re-importing
`OPERATING_AREA_BBOX`/`REF_LAT_DEG` directly) so a `RegionPack` other than
the Med's can drive the exact same code paths.

Two representations of "the Med pack" exist by design, not accident:
`MED_PACK` below is a plain Python constant, built entirely from values
already imported at module load time -- zero file I/O, because
`PlanRequest.region_pack`'s default must not gain a working-directory-
relative file dependency (`optimise()` falls back to `MED_PACK`, not to
loading a YAML file -- see `core/optimiser.py`). `data/region_packs/med.yaml`
is the same data in the on-disk form the API/deployment layer's
`Settings.region_packs_path` actually loads. `tests/test_regionpack.py`'s
drift guard (`RegionPack.from_yaml(...) == MED_PACK`) is what keeps the
two from silently diverging.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from core.corridors import CORRIDOR_REGISTRY, PORTS, REF_LAT_DEG, Corridor
from core.geography import (
    DEFAULT_BATHYMETRY_PATH,
    DEFAULT_COASTLINE_PATH,
    DEFAULT_NOGO_PATH,
    DEFAULT_TSS_PATH,
    OPERATING_AREA_BBOX,
)
from core.lattice import (
    DEFAULT_MIN_NAVIGABLE_EDGE_FRACTION,
    DEFAULT_MIN_REFINEMENT_STEP_NM,
)
from core.units import LatLon

# Default weather npz path for the Med pack -- matches api/config.py's own
# `Settings.weather_npz_path` default; not imported from there to avoid a
# core/ -> api/ dependency (core/ never imports api/).
MED_WEATHER_NPZ_PATH = "data/weather/ecmwf_western_med.npz"


@dataclass(frozen=True)
class RegionPack:
    pack_id: str
    name: str
    bbox: tuple[float, float, float, float]  # lon_min, lat_min, lon_max, lat_max
    ref_lat_deg: float
    coastline_path: str
    bathymetry_path: str
    nogo_path: str
    tss_path: str
    weather_npz_path: str
    ports: dict[str, LatLon] = field(default_factory=dict)
    default_origin: LatLon | None = None
    default_destination: LatLon | None = None
    # Med-tuned lattice search knobs -- pack-overridable. `min_navigable_edge_fraction`/
    # `min_refinement_step_nm` (ticket 0.8's adaptive-refinement knobs)
    # default to the Med's own tuned values (CLAUDE.md's Bonifacio gotcha
    # has the full empirical-tuning story; there's no principled reason
    # these are right for a different coastline's degradation profile, but
    # no invented UK-specific number either -- new packs start from the
    # same values and any infeasibility that surfaces is a reportable
    # finding, not something to silently tune away).
    #
    # `lane_turn_rate_nm: None` (ticket L1) -- unlike the two above, this
    # is *not* a Med-value default a new pack silently inherits: `None`
    # means "derive from this pack's own passage geometry"
    # (`core.lattice.build_lattice`'s own docstring has the formula and
    # the empirical grounding, `docs/plans/ticket-L1.md`). Still a real
    # override -- a pack whose coastline genuinely needs Bonifacio-style
    # empirical tuning can still set an explicit nm value here, the same
    # escape hatch R1 already established for the other two knobs.
    lane_turn_rate_nm: float | None = None
    min_navigable_edge_fraction: float = DEFAULT_MIN_NAVIGABLE_EDGE_FRACTION
    min_refinement_step_nm: float = DEFAULT_MIN_REFINEMENT_STEP_NM
    # Empty for every pack except "med" -- hand-drawn corridors are
    # Med-only legacy (ROADMAP.md's R1 row). Names are resolved through
    # `core.corridors.CORRIDOR_REGISTRY` (`_resolve_corridor` below) --
    # YAML can't hold a function literal, and this is also what
    # `data/region_packs/*.yaml` stores on disk.
    legacy_corridors: tuple[tuple[LatLon, LatLon, str], ...] = ()
    # Ticket C1: None (default, every pack including "med") -> currents
    # stay at exactly zero, current_u_ms/current_v_ms's original ticket
    # B2 behaviour, unchanged. Set to a real CMEMS dataset_id (see
    # ingest/fetch_currents_cmems.py's module docstring for the verified
    # real ids) to opt a pack into ingest/fetch_all_packs.py's per-pack
    # currents fetch+merge step.
    currents_dataset_id: str | None = None

    @classmethod
    def from_yaml(cls, path: str | Path) -> RegionPack:
        with open(path) as f:
            raw = yaml.safe_load(f)
        return cls.from_dict(raw)

    @classmethod
    def from_dict(cls, raw: dict) -> RegionPack:
        def _latlon(values: list[float] | None) -> LatLon | None:
            return LatLon(*values) if values is not None else None

        ports = {name: LatLon(*coords) for name, coords in raw.get("ports", {}).items()}
        legacy_corridors = tuple(
            (
                LatLon(*entry["origin"]),
                LatLon(*entry["destination"]),
                _validate_corridor(entry["corridor"]),
            )
            for entry in raw.get("legacy_corridors", [])
        )
        return cls(
            pack_id=raw["pack_id"],
            name=raw["name"],
            bbox=tuple(raw["bbox"]),
            ref_lat_deg=raw["ref_lat_deg"],
            coastline_path=raw["coastline_path"],
            bathymetry_path=raw["bathymetry_path"],
            nogo_path=raw["nogo_path"],
            tss_path=raw["tss_path"],
            weather_npz_path=raw["weather_npz_path"],
            ports=ports,
            default_origin=_latlon(raw.get("default_origin")),
            default_destination=_latlon(raw.get("default_destination")),
            lane_turn_rate_nm=raw.get("lane_turn_rate_nm"),
            min_navigable_edge_fraction=raw.get(
                "min_navigable_edge_fraction", DEFAULT_MIN_NAVIGABLE_EDGE_FRACTION
            ),
            min_refinement_step_nm=raw.get(
                "min_refinement_step_nm", DEFAULT_MIN_REFINEMENT_STEP_NM
            ),
            legacy_corridors=legacy_corridors,
            currents_dataset_id=raw.get("currents_dataset_id"),
        )


def _validate_corridor(name: str) -> str:
    """Resolves `name` through `CORRIDOR_REGISTRY` purely to validate it
    at pack-load time (raising a clear error immediately, not a confusing
    `KeyError` from inside `optimise()`'s corridor-DP loop much later) --
    the name itself, not the resolved `Callable`, is what `RegionPack`
    stores, so `MED_PACK` (built in Python, never through this function)
    and a YAML-loaded pack compare equal on this field with plain string
    equality."""
    if name not in CORRIDOR_REGISTRY:
        raise ValueError(
            f"unknown corridor {name!r} in region pack manifest -- known corridors: "
            f"{sorted(CORRIDOR_REGISTRY)}"
        )
    return name


def resolve_pack_endpoint(
    region_pack: RegionPack, origin: LatLon | None, destination: LatLon | None
) -> tuple[LatLon, LatLon]:
    """Shared by api/convert.py's main-process fail-fast validation and
    api/state.py's run_plan_job worker-side construction (both
    independently build a `core.optimiser.PlanRequest` from request-shaped
    data -- a pre-existing duplication this ticket doesn't introduce, see
    `plan_request_from_in`'s docstring). Omitted origin/destination fall
    back to the pack's own `default_origin`/`default_destination`
    (exactly `DEFAULT_ORIGIN`/`DEFAULT_DESTINATION` for "med", so zero
    behaviour change for existing callers) -- raises rather than silently
    defaulting to a different pack's endpoints when the target pack has
    none configured."""
    if origin is None:
        if region_pack.default_origin is None:
            raise ValueError(
                f"region pack {region_pack.pack_id!r} has no default origin -- "
                "origin must be supplied explicitly"
            )
        origin = region_pack.default_origin
    if destination is None:
        if region_pack.default_destination is None:
            raise ValueError(
                f"region pack {region_pack.pack_id!r} has no default destination -- "
                "destination must be supplied explicitly"
            )
        destination = region_pack.default_destination
    return origin, destination


def resolve_corridor(name: str) -> Callable[[], Corridor]:
    """Used by `core.optimiser`'s corridor-DP loop to turn a
    `RegionPack.legacy_corridors` entry's name back into the actual
    `Corridor`-building function."""
    return CORRIDOR_REGISTRY[name]


MED_PACK = RegionPack(
    pack_id="med",
    name="Western Mediterranean",
    bbox=OPERATING_AREA_BBOX,
    ref_lat_deg=REF_LAT_DEG,
    coastline_path=DEFAULT_COASTLINE_PATH,
    bathymetry_path=DEFAULT_BATHYMETRY_PATH,
    nogo_path=DEFAULT_NOGO_PATH,
    tss_path=DEFAULT_TSS_PATH,
    weather_npz_path=MED_WEATHER_NPZ_PATH,
    ports=PORTS,
    default_origin=PORTS["antibes"],
    default_destination=PORTS["portocervo"],
    min_navigable_edge_fraction=DEFAULT_MIN_NAVIGABLE_EDGE_FRACTION,
    min_refinement_step_nm=DEFAULT_MIN_REFINEMENT_STEP_NM,
    legacy_corridors=(
        (PORTS["antibes"], PORTS["portocervo"], "corridor_west"),
        (PORTS["antibes"], PORTS["portocervo"], "corridor_east"),
    ),
)
